services:
  blazorcrud:
    image: blazor-crud
    build: .
    ports:
        - 8080:80

  sqldb: 
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: yourStrong!Password123
      ACCEPT_EULA: Y
      MSSQL_PID: Express 
    volumes:
      - sqldata:/var/opt/mssql/data
    user: root

# Named volume for data persistence
volumes:
  sqldata: